language: objective-c
osx_image: xcode8

env:
   global:
   - LANG=en_US.UTF-8

   - PROJECT="JSQDataSourcesKit.xcodeproj"

   - IOS_SCHEME="JSQDataSourcesKit-iOS"
   - TVOS_SCHEME="JSQDataSourcesKit-tvOS"

   - IOS_SDK=iphonesimulator10.0
   - TVOS_SDK=appletvsimulator10.0

   matrix:
   - DESTINATION="OS=8.1,name=iPhone 4s"     SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES"  BUILD_EXAMPLE="YES" POD_LINT="YES"
   - DESTINATION="OS=8.2,name=iPhone 5"      SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES"  BUILD_EXAMPLE="NO"  POD_LINT="NO"
   - DESTINATION="OS=8.3,name=iPhone 5s"     SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES"  BUILD_EXAMPLE="NO"  POD_LINT="NO"
   - DESTINATION="OS=8.4,name=iPhone 6"      SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES"  BUILD_EXAMPLE="YES" POD_LINT="NO"

   - DESTINATION="OS=9.0,name=iPhone 6 Plus"  SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="NO"
   - DESTINATION="OS=9.1,name=iPhone 6s"      SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO"
   - DESTINATION="OS=9.2,name=iPhone 6s Plus" SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO"
   - DESTINATION="OS=9.3,name=iPhone 7"       SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="NO"
  - DESTINATION="OS=10.0,name=iPhone 7 Plus"  SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="NO"

   - DESTINATION="OS=8.1,name=iPad 2"       SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="NO"
   - DESTINATION="OS=8.4,name=iPad 2"       SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO"
   - DESTINATION="OS=9.0,name=iPad Retina"  SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="NO"
   - DESTINATION="OS=9.1,name=iPad Air"     SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO"
   - DESTINATION="OS=9.2,name=iPad Air 2"   SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO"
   - DESTINATION="OS=9.3,name=iPad Pro"     SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO"
   - DESTINATION="OS=10,name=iPad Air 2"    SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO"


   - DESTINATION="OS=9.0,name=Apple TV 1080p"  SDK="$TVOS_SDK" SCHEME="$TVOS_SCHEME" RUN_TESTS="NO" BUILD_EXAMPLE="NO" POD_LINT="NO"
   - DESTINATION="OS=9.2,name=Apple TV 1080p"  SDK="$TVOS_SDK" SCHEME="$TVOS_SCHEME" RUN_TESTS="NO" BUILD_EXAMPLE="NO" POD_LINT="NO"
   - DESTINATION="OS=10.0,name=Apple TV 1080p" SDK="$TVOS_SDK" SCHEME="$TVOS_SCHEME" RUN_TESTS="NO" BUILD_EXAMPLE="NO" POD_LINT="NO"

script:
- if [ $POD_LINT == "YES" ]; then
      pod spec lint;
      pod lib lint;
  fi


- if [ $BUILD_EXAMPLE == "YES" ]; then
      xcodebuild clean build -project Example/Example.xcodeproj -scheme Example -sdk "$SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO | xcpretty -c;
  fi


- if [ $RUN_TESTS == "YES" ]; then
      xcodebuild test -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c;
  else
      xcodebuild clean build -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c;
  fi


# Build for reporting test coverage
# - if [ $RUN_TESTS == "YES" ]; then
#       xcodebuild test -project JSQDataSourcesKit.xcodeproj -scheme JSQDataSourcesKit-iOS -sdk iphonesimulator;
#   fi

after_success:
- bash <(curl -s https://codecov.io/bash)
